import { normalizeCityName } from '@/config/fleet-cities';

/**
 * Major cities and towns across India, sorted alphabetically.
 * Used for customer booking city selection.
 */
export const INDIAN_CITIES: readonly string[] = [
  'Agartala',
  'Agra',
  'Ahmedabad',
  'Ahmednagar',
  'Aizawl',
  'Ajmer',
  'Akola',
  'Alappuzha',
  'Aligarh',
  'Allahabad',
  'Alwar',
  'Ambala',
  'Ambikapur',
  'Amravati',
  'Amritsar',
  'Anand',
  'Anantapur',
  'Anantnag',
  'Arrah',
  'Asansol',
  'Aurangabad',
  'Azamgarh',
  'Bahraich',
  'Balasore',
  'Ballari',
  'Baramulla',
  'Bareilly',
  'Bathinda',
  'Begusarai',
  'Belagavi',
  'Berhampur',
  'Bettiah',
  'Bhagalpur',
  'Bharuch',
  'Bhavnagar',
  'Bhilai',
  'Bhimavaram',
  'Bhiwandi',
  'Bhopal',
  'Bhubaneswar',
  'Bidar',
  'Bihar Sharif',
  'Bikaner',
  'Bilaspur',
  'Bokaro',
  'Bulandshahr',
  'Chandigarh',
  'Chandrapur',
  'Chennai',
  'Chhapra',
  'Chhindwara',
  'Chittoor',
  'Coimbatore',
  'Cuttack',
  'Daman',
  'Darjeeling',
  'Davanagere',
  'Dehradun',
  'Deoghar',
  'Dhanbad',
  'Dharamshala',
  'Dibrugarh',
  'Dimapur',
  'Diu',
  'Durg',
  'Durgapur',
  'Eluru',
  'Erode',
  'Etawah',
  'Faridabad',
  'Firozabad',
  'Gandhinagar',
  'Gangtok',
  'Gaya',
  'Ghaziabad',
  'Giridih',
  'Gorakhpur',
  'Gulbarga',
  'Guntur',
  'Gurugram',
  'Guwahati',
  'Gwalior',
  'Haldwani',
  'Haridwar',
  'Hazaribagh',
  'Hisar',
  'Howrah',
  'Hubballi',
  'Hyderabad',
  'Imphal',
  'Indore',
  'Itanagar',
  'Jabalpur',
  'Jagdalpur',
  'Jaipur',
  'Jalandhar',
  'Jalgaon',
  'Jammu',
  'Jamnagar',
  'Jamshedpur',
  'Jhansi',
  'Jodhpur',
  'Jorhat',
  'Junagadh',
  'Kadapa',
  'Kakinada',
  'Kalyan',
  'Kannur',
  'Kanpur',
  'Karaikal',
  'Kargil',
  'Karimnagar',
  'Karnal',
  'Kavaratti',
  'Khammam',
  'Kochi',
  'Kohima',
  'Kolhapur',
  'Kolkata',
  'Kollam',
  'Korba',
  'Kota',
  'Kozhikode',
  'Kurnool',
  'Leh',
  'Lucknow',
  'Ludhiana',
  'Madurai',
  'Mahbubnagar',
  'Malappuram',
  'Mandi',
  'Mangaluru',
  'Margao',
  'Mathura',
  'Meerut',
  'Mehsana',
  'Moradabad',
  'Mumbai',
  'Munger',
  'Muzaffarnagar',
  'Muzaffarpur',
  'Mysuru',
  'Nagpur',
  'Nahan',
  'Naharlagun',
  'Nanded',
  'Nashik',
  'Nellore',
  'New Delhi',
  'Nizamabad',
  'Noida',
  'Ongole',
  'Panaji',
  'Panipat',
  'Pasighat',
  'Patna',
  'Patiala',
  'Prayagraj',
  'Puducherry',
  'Pune',
  'Puri',
  'Purnia',
  'Raichur',
  'Raipur',
  'Rajkot',
  'Ranchi',
  'Ratlam',
  'Rewa',
  'Rishikesh',
  'Rohtak',
  'Roorkee',
  'Rourkela',
  'Sagar',
  'Saharanpur',
  'Saharsa',
  'Salem',
  'Samastipur',
  'Sambalpur',
  'Sasaram',
  'Satna',
  'Shillong',
  'Shimla',
  'Shivamogga',
  'Silchar',
  'Siliguri',
  'Silvassa',
  'Solan',
  'Solapur',
  'Sonipat',
  'Srinagar',
  'Surat',
  'Tawang',
  'Thane',
  'Thanjavur',
  'Thiruvananthapuram',
  'Thrissur',
  'Tiruchirappalli',
  'Tirunelveli',
  'Tirupati',
  'Tiruppur',
  'Tura',
  'Udaipur',
  'Udhampur',
  'Udupi',
  'Ujjain',
  'Vadodara',
  'Varanasi',
  'Vasco Da Gama',
  'Vellore',
  'Vijayawada',
  'Visakhapatnam',
  'Warangal',
  'Yamunanagar',
  'Yavatmal',
] as const;

/** Common alternate spellings mapped to canonical dropdown values. */
const INDIAN_CITY_ALIASES: Readonly<Record<string, string>> = {
  bangalore: 'Bengaluru',
  bengaluru: 'Bengaluru',
  allahabad: 'Prayagraj',
  prayagraj: 'Prayagraj',
  calcutta: 'Kolkata',
  kolkata: 'Kolkata',
  bombay: 'Mumbai',
  mumbai: 'Mumbai',
  madras: 'Chennai',
  chennai: 'Chennai',
  gurgaon: 'Gurugram',
  gurugram: 'Gurugram',
  baroda: 'Vadodara',
  vadodara: 'Vadodara',
  trivandrum: 'Thiruvananthapuram',
  thiruvananthapuram: 'Thiruvananthapuram',
  calicut: 'Kozhikode',
  kozhikode: 'Kozhikode',
  cochin: 'Kochi',
  kochi: 'Kochi',
  mysore: 'Mysuru',
  mysuru: 'Mysuru',
  pondicherry: 'Puducherry',
  puducherry: 'Puducherry',
  cawnpore: 'Kanpur',
  kanpur: 'Kanpur',
  benares: 'Varanasi',
  varanasi: 'Varanasi',
  simla: 'Shimla',
  shimla: 'Shimla',
  newdelhi: 'New Delhi',
};

const INDIAN_CITY_LOOKUP = new Map<string, string>([
  ...INDIAN_CITIES.map((city) => [normalizeCityName(city).toLowerCase(), city] as const),
  ...Object.entries(INDIAN_CITY_ALIASES).map(([alias, city]) => [alias, city] as const),
]);

/** Resolves user input to a canonical Indian city name, if recognised. */
export function resolveIndianCity(value: string): string | null {
  const normalized = normalizeCityName(value);
  if (!normalized) {
    return null;
  }

  return INDIAN_CITY_LOOKUP.get(normalized.toLowerCase()) ?? null;
}

/** Case-insensitive filter for the city picker search field. */
export function filterIndianCities(query: string): string[] {
  const trimmed = query.trim().toLowerCase();
  if (!trimmed) {
    return [...INDIAN_CITIES];
  }

  return INDIAN_CITIES.filter((city) => city.toLowerCase().includes(trimmed));
}
